project:
  type: website

website:
  title: "Pragmatic Data Science"
  body-header: "\\[Mihai Bizovi | Head of Data Science \\@AdoreMe\\]"
  favicon: img/favicon.jpeg
  open-graph:
    locale: es_ES
    site-name: Quarto
  google-analytics: "G-TNKQREJHQW"

  navbar:
    search: true
    left:
      - href: index.qmd
        text: "Course Home"
      - sidebar:fundamentals
      - sidebar:causal
      - sidebar:ml
      - sidebar:engineering
    right: 
      - icon: github
        href: https://github.com/bizovi/data-mining-ase
      - icon: linkedin
        href: https://www.linkedin.com/in/bizovi-mihai-56982abb/
      - icon: bi-journal-bookmark
        href: https://blog.economic-cybernetics.com/

  sidebar:
    - id: fundamentals
      title: "The fundamenals"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - href: 01_fundamentals/background.qmd
          text: "Data Science in Business Context"
        - href: 01_fundamentals/stat_foundations.qmd
          text: "Statistical foundations"
        - href: 01_fundamentals/bolt.qmd
          text: "Case Study: Decisions at Bolt and Uber"
        - href: 01_fundamentals/adoreme.qmd
          text: "Case Study: AI at AdoreMe (e-commerce)" 
        - href: 01_fundamentals/lab_01.qmd
          text: "Lab: Recap of tidyverse and stats"
        - href: 01_fundamentals/slides.qmd
          text: "Slides: Data Science in Context"
    - id: causal
      title: "Causal Inference"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - href: 02_causality/background.qmd
          text: "Experiment Design and A/B Testing"
        - href: 02_causality/power.qmd
          text: "Advanced Topics in Experiment Design"
        - href: 02_causality/lab.qmd
          text: "Lab: Deep Dive into Hypothesis testing"
    - id: ml
      title: "Machine Learning"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - href: 03_ml/what_is_learning.qmd
          text: "What is machine learning"
    - id: engineering
      title: "Engineering"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - href: 04_engineering/happy_clients.qmd
          text: "How can we keep our clients happy?"

  page-navigation: true
  page-footer:
    left: "The course I wish I had when getting started. Built with ❤️ by Mihai Bizovi"

bibliography: references.bib
highlight-style: pygments

format:
  html:
    theme: 
      light: simplex
      dark: cyborg
    page-layout: full
    css: styles.css
    toc-location: left
    
editor: visual

reference-location: margin
  
comments:
  hypothesis: 
    theme: clean

# comments:
#   utterances:
#     repo: bizovi/data-mining-ase