project:
  type: website

website:
  title: "Decision Science Course"
  favicon: img/favicon.jpeg
  open-graph:
    locale: es_ES
    site-name: "Pragmatic Data Science"
  google-analytics: "G-TNKQREJHQW"

  navbar:
    search: true
    left:
      - href: roadmap.qmd
        text: "Roadmap"
      - href: references.qmd
        text: "Resources"
    right: 
      - href: about_me.qmd
        text: "About Me"
      - icon: bi-journal-bookmark
        href: https://blog.economic-cybernetics.com/
        text: "Blog"
      - icon: github
        href: https://github.com/bizovi/decision-making
      - icon: linkedin
        href: https://www.linkedin.com/in/bizovi-mihai-56982abb/

  sidebar:
    # - id: fundamentals
    title: "Decision-Making for the brave and true"
    style: "docked"
    background: light
    collapse-level: 2

    contents: 
      - href: index.qmd
        text: "i. Course Philosophy"
      - href: roadmap.qmd
        text: "ii. Course Roadmap"
      - section: "1. Business Decisions and Probability"
        href: 01_fundamentals/background.qmd
        contents:
        - href: 01_fundamentals/background.qmd
          text: "Data Science in Business Context"
        - href: 01_fundamentals/prerequisites.qmd
          text: "Prerequisites: Why did you study all of that?"
        - href: 01_fundamentals/stat_foundations.qmd
          text: "Foundations of Probability"
        - href: 01_fundamentals/learning.qmd
          text: "Learning from Data: Intuition and Bias"
      - section: "2a. Applied Bayesian Statistics"
        href: references.qmd
        contents:
          - href: references.qmd
            text: "Study Resources"      
      - section: "2b. A/B Testing and Causal Inference"
      - section: "3. Probabilistic ML and Deep Learning"
      - section: "4. Full Stack Data Apps"


  page-navigation: true
  page-footer:
    left: "The course I wish I had when getting started. Built with ❤️ by Mihai Bizovi"

bibliography: references.bib
highlight-style: pygments

format:
  html:
    theme: 
      light: yeti # simplex
      dark: cyborg
    page-layout: full
    css: styles.css
    toc-location: left
    
editor: source
reference-location: margin
  
comments:
  hypothesis: 
    theme: clean