project:
  type: website

website:
  title: "Decision Science Course"
  favicon: img/favicon.jpeg
  open-graph:
    locale: es_ES
    site-name: "Pragmatic Data Science"
  google-analytics: "G-TNKQREJHQW"

  navbar:
    search: true
    left:
      - href: references.qmd
        text: "2a. Bayes"
    right: 
      - href: about_me.qmd
        text: "About Me"
      - icon: bi-journal-bookmark
        href: https://blog.economic-cybernetics.com/
        text: "Blog"
      - icon: github
        href: https://github.com/bizovi/decision-making
      - icon: linkedin
        href: https://www.linkedin.com/in/bizovi-mihai-56982abb/

  sidebar:
    # - id: fundamentals
    title: "Decision-Making for the brave and true"
    style: "docked"
    background: light
    collapse-level: 1

    contents: 
      - href: index.qmd
        text: "i. Introduction"
      - href: philosophy.qmd
        text: "ii. Course Philosophy"
      - section: "1. Business Decisions and Probability"
        href: 01_fundamentals/background.qmd
        contents:
        - href: 01_fundamentals/background.qmd
          text: "1. Data Science in Business Context"
        - href: 01_fundamentals/roadmap.qmd
          text: "2. Syllabus & Roadmap"
        - href: 01_fundamentals/prerequisites.qmd
          text: "3. Prerequisites: Why did you study all of that?"
        - href: 01_fundamentals/stat_foundations.qmd
          text: "4. Foundations of Probability"
        - href: 01_fundamentals/learning.qmd
          text: "5. Learning from Data: Intuition and Bias"
      - section: "2a. Applied Bayesian Statistics"
        href: references.qmd
        contents:
          - href: 02_causality/roadmap.qmd
            text: "1. Syllabus & Roadmap"
          - href: references.qmd
            text: "2. Building Blocks"
          - href: references.qmd#groups-and-partial-pooling  
            text: "3. Groups and Partial Pooling"
          - href: references.qmd#gaussian-linear-regression
            text: "4. Gaussian Linear Regression"
          - href: references.qmd#generalized-linear-models
            text: "5. Generalized Linear Models"
          - href: references.qmd#hierarchical-glms
            text: "6. Hierarchical GLMs"
      - section: "2b. Hypotheses and A/B Testing"
        href: 02_causality/roadmap_abtest.qmd
        contents:
          - href: 02_causality/roadmap_abtest.qmd
            text: "1. Syllabus & Roadmap"
          - href: 02_causality/ab_testing.qmd
            text: "2. A/B Testing study resources"
      # - section: "2c. Causal Inference with DAGs (TBD)"
      #   href: index.qmd#what-will-you-learn
      #   contents:
      #     - href: index.qmd#what-will-you-learn
      #       text: "1. Syllabus & Roadmap"
      - section: "3a. Probabilistic Machine Learning"
        href: 03_ml/roadmap.qmd
        contents:
          - href: 03_ml/roadmap.qmd
            text: "1. Syllabus & Roadmap"
      # - section: "3b. Deep Learning and Special Topics (TBD)"
      #   href: 03_ml/roadmap.qmd
      #   contents:
      #     - href: 03_ml/roadmap.qmd
      #       text: "1. Syllabus & Roadmap"
      - section: "4. Full Stack Data Apps"
        href: 04_engineering/roadmap.qmd
        contents:
          - href: 04_engineering/roadmap.qmd
            text: "1. Syllabus & Roadmap"
      # - href: references.qmd
      #   text: "X. Resources"


  page-navigation: true
  page-footer:
    left: "The course I wish I had when getting started. Built with ❤️ by Mihai Bizovi"

bibliography: references.bib
highlight-style: pygments

format:
  html:
    theme: 
      light: yeti # simplex
      dark: cyborg
    page-layout: full
    css: styles.css
    toc-location: left
    
editor: source
reference-location: margin
  
comments:
  hypothesis: 
    theme: clean