project:
  type: website

website:
  title: "Pragmatic Data Science"
  favicon: img/favicon.jpeg
  open-graph:
    locale: es_ES
    site-name: Quarto
  google-analytics: "G-TNKQREJHQW"

  navbar:
    search: true
    left:
      - href: roadmap.qmd
        text: "Roadmap"
      - sidebar:fundamentals
      - href: references.qmd
        text: "Resources"
      - href: about_me.qmd
        text: "About Me"
      # - sidebar:causal
      # - sidebar:ml
      # - sidebar:engineering
    right: 
      - icon: github
        href: https://github.com/bizovi/data-mining-ase
      - icon: linkedin
        href: https://www.linkedin.com/in/bizovi-mihai-56982abb/
      - icon: bi-journal-bookmark
        href: https://blog.economic-cybernetics.com/

  sidebar:
    - id: fundamentals
      title: "The fundamenals"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - href: 01_fundamentals/background.qmd
          text: "Data Science in Business Context"
        - href: 01_fundamentals/learning.qmd
          text: "Learning from Data: Intuition and Bias"
        - href: 01_fundamentals/prerequisites.qmd
          text: "Prereq: Why did you study all of that?"
        - href: 01_fundamentals/stat_foundations.qmd
          text: "Foundations of Probability"
        # - href: 01_fundamentals/bolt.qmd
        #   text: "Case Study: Decisions at Bolt and LRB"
        # - href: 01_fundamentals/adoreme.qmd
        #   text: "Case Study: AI at AdoreMe (e-commerce)" 
        # - href: 01_fundamentals/lab_01.qmd
        #   text: "Lab: Recap of tidyverse and stats"

    # - id: causal
    #   title: "Causal Inference"
    #   style: "docked"
    #   background: light
    #   collapse-level: 2
    #   contents:
    #     - href: 02_causality/background.qmd
    #       text: "Experiment Design and A/B Testing"
    #     - href: 02_causality/power.qmd
    #       text: "Advanced Topics in Experiment Design"
    #     - href: 02_causality/lab.qmd
    #       text: "Lab: Deep Dive into Hypothesis testing"
    # - id: ml
    #   title: "Machine Learning"
    #   style: "docked"
    #   background: light
    #   collapse-level: 2
    #   contents:
    #     - href: 03_ml/what_is_learning.qmd
    #       text: "What is machine learning"
    # - id: engineering
    #   title: "Engineering"
    #   style: "docked"
    #   background: light
    #   collapse-level: 2
    #   contents:
    #     - href: 04_engineering/happy_clients.qmd
    #       text: "How can we keep our clients happy?"

  page-navigation: true
  page-footer:
    left: "The course I wish I had when getting started. Built with ❤️ by Mihai Bizovi"

bibliography: references.bib
highlight-style: pygments

format:
  html:
    theme: 
      light: simplex
      dark: cyborg
    page-layout: full
    css: styles.css
    toc-location: left
    
editor: visual

reference-location: margin
  
comments:
  hypothesis: 
    theme: clean

# comments:
#   utterances:
#     repo: bizovi/data-mining-ase