project:
  type: book

book:
  title: "Pragmatic Data Science"
  author: "Mihai Bizovi"
  date: "12/5/2022"

  search: true
  repo-url: https://github.com/bizovi/data-mining-ase
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]

  sidebar:
    style: docked
    background: light

  chapters:
    - index.qmd
    - part: "Part I: The fundamenals"
      chapters:
        - href: 01_fundamentals/background.qmd
          text: "Background"
        - href: 01_fundamentals/stat_foundations.qmd
          text: "Statistical foundations"
        - href: 01_fundamentals/lab_01.qmd
          text: "Lab1: Recap of tidyverse"
    - part: "Part II: Experiment Design"
      chapters:
        - background.qmd
        - href: lab_02.qmd
          text: A/B testing
    # - part: "Part III: Statistical Learning"
    #   chapters:
    #     - background.qmd
    #     - lab_01.qmd
    # - part: "Part IV: Unsupervised Learning"
    #   chapters:
    #     - lab_01.qmd
    # - part: "Part V: Generalised linear madness"
    #   chapters:
    #     - lab_01.qmd
    # - part: "Part VI: Miscellaneous"
    #   chapters:
    #     - lab_01.qmd

    # - intro.qmd
    # - summary.qmd
    - references.qmd
  page-navigation: true

bibliography: references.bib

highlight-style: pygments

format:
  html:
    theme: simplex # cosmo
  pdf:
    documentclass: scrreprt

editor: visual

reference-location: margin
  
comments:
  hypothesis: true