project:
  type: book

book:
  title: "Pragmatic Data Science"
  author: "Mihai Bizovi | Head of Data Science (AdoreMe)"
  date: "12/5/2022"

  search: true
  repo-url: https://github.com/bizovi/data-mining-ase
  # repo-actions: []
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  favicon: img/favicon.jpeg

  sidebar:
    style: docked
    background: light

  chapters:
    - href: index.qmd
      text: "Course Home"
    - part: "Part I: The fundamenals"
      chapters:
        - href: 01_fundamentals/background.qmd
          text: "Data Science in Business Context"
        - href: 01_fundamentals/stat_foundations.qmd
          text: "Statistical foundations"
        - href: 01_fundamentals/bolt.qmd
          text: "Case Study: Decisions at Bolt and Uber"
        - href: 01_fundamentals/adoreme.qmd
          text: "Case Study: AI at AdoreMe (e-commerce)" 
        - href: 01_fundamentals/lab_01.qmd
          text: "Lab: Recap of tidyverse and stats"
    - part: "Part II: Elements of Causal Inference"
      chapters:
        - href: 02_causality/background.qmd
          text: "Experiment Design and A/B Testing"
        - href: 02_causality/power.qmd
          text: "Advanced Topics in Experiment Design"
        - href: 02_causality/lab.qmd
          text: "Lab: Deep Dive into Hypothesis testing"

    # - part: "Part III: Statistical Learning"
    #   chapters:
    #     - background.qmd
    #     - lab_01.qmd
    # - part: "Part IV: Unsupervised Learning"
    #   chapters:
    #     - lab_01.qmd
    # - part: "Part V: Generalised linear madness"
    #   chapters:
    #     - lab_01.qmd
    # - part: "Part VI: Miscellaneous"
    #   chapters:
    #     - lab_01.qmd

    # - intro.qmd
    # - summary.qmd
    - references.qmd
  page-navigation: true

bibliography: references.bib

highlight-style: pygments

format:
  html:
    theme: simplex # cosmo
    # max-width: 1600px
    # margin-left: 30px
    page-layout: article # full
    css: styles.css
    toc-location: body
    
editor: visual

reference-location: margin
  
comments:
  hypothesis: true